"""add patient_journey and visit journey fields

Revision ID: b1a7212504d3
Revises: 8ff31c6a2004
Create Date: 2026-07-18 16:53:00.805940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a7212504d3'
down_revision: Union[str, Sequence[str], None] = '8ff31c6a2004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_journey',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('visit_kind', sa.Enum('New', 'Returning', 'Follow-up', name='journeykindenum'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Cancelled', name='journeystatusenum'), nullable=False),
    sa.Column('current_step_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_journey_patient_id'), 'patient_journey', ['patient_id'], unique=False)
    op.add_column('visit', sa.Column('journey_id', sa.String(length=36), nullable=True))
    op.add_column('visit', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('step_purpose', sa.String(length=255), nullable=True))
    op.add_column('visit', sa.Column('arrived_at', sa.DateTime(), nullable=True))
    op.add_column('visit', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('visit', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_visit_journey_id'), 'visit', ['journey_id'], unique=False)
    op.create_foreign_key(None, 'visit', 'patient_journey', ['journey_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_index(op.f('ix_visit_journey_id'), table_name='visit')
    op.drop_column('visit', 'completed_at')
    op.drop_column('visit', 'started_at')
    op.drop_column('visit', 'arrived_at')
    op.drop_column('visit', 'step_purpose')
    op.drop_column('visit', 'sequence')
    op.drop_column('visit', 'journey_id')
    op.drop_index(op.f('ix_patient_journey_patient_id'), table_name='patient_journey')
    op.drop_table('patient_journey')
    # ### end Alembic commands ###

    # Drop the native ENUM types Alembic creates implicitly but does not remove,
    # so the downgrade fully reverses the upgrade and re-upgrade succeeds.
    for enum_name in ("journeykindenum", "journeystatusenum"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
